In [ ]:
import anndata as an
import scanpy as sc
import scarches as sca
import numpy as np

In [ ]:
import torch
torch.set_printoptions(precision=3, sci_mode=False, edgeitems=7)

In [26]:
hips = an.read_h5ad("dataset/hiPSC.h5ad") 

c:\Users\Mick\PycharmProjects\BPEXA\in_house_data\venv\in-house\.venv\Lib\site-packages\anndata\compat\__init__.py:358: FutureWarning: Moving element from .uns['neighbors']['distances'] to .obsp['distances'].

This is where adjacency matrices should go now.
  warn(


Converting dataset

In [27]:
for col in hips.obs.columns:
    if hips.obs[col].dtype == np.float32:
        hips.obs[col] = hips.obs[col].astype(np.int64)
    if hips.obs[col].dtype == np.int32:
        hips.obs[col] = hips.obs[col].astype(np.int64)
hips.X.astype(np.int64)

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 24518519 stored elements and shape (4694, 23543)>

In [28]:
for i in hips.obs:
    print(type(hips.obs[i][0]))

<class 'str'>
<class 'numpy.float64'>
<class 'numpy.int64'>
<class 'str'>
<class 'str'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'str'>
<class 'str'>
<class 'numpy.int64'>


In [29]:
sca.utils.add_annotations(hips,"metadata/reactome.gmt", min_genes=12, clean=True)

In [30]:
hips._inplace_subset_var(hips.varm["I"].sum(1)>0)

In [31]:
sc.pp.normalize_total(hips)

In [32]:
sc.pp.log1p(hips)
hips.obs

orig.ident  nCount_RNA  \
batch_2_A_AAACCCAAGGTAATCA-1            SeuratProject     48806.0   
batch_2_A_AAAGGATCATCCAATG-1            SeuratProject      5460.0   
batch_2_A_AAAGGATGTGGTCAAG-1            SeuratProject     32899.0   
batch_2_A_AAAGGTAGTGTCATCA-1            SeuratProject     37327.0   
batch_2_A_AAATGGACATATCTGG-1            SeuratProject     18633.0   
...                                               ...         ...   
batch_1_sample_120H_TTTACTGCATCCGCGA-1  SeuratProject     14013.0   
batch_1_sample_120H_TTTCACATCAGCCCAG-1  SeuratProject     21173.0   
batch_1_sample_120H_TTTCAGTAGTACAGAT-1  SeuratProject     22107.0   
batch_1_sample_120H_TTTGATCAGCTCCATA-1  SeuratProject     12806.0   
batch_1_sample_120H_TTTGTTGAGTTGGCGA-1  SeuratProject     32140.0   

                                        nFeature_RNA   run sample_name  \
batch_2_A_AAACCCAAGGTAATCA-1                    6892  0h_A   iPSC_99_4   
batch_2_A_AAAGGATCATCCAATG-1                    2307  0h_A   iPSC_99_4   
batch_2_A_AAAGGATGTGGTCAAG-1                    5707  0h_A   iPSC_99_4   
batch_2_A_AAAGGTAGTGTCATCA-1                    6069  0h_A   iPSC_99_4   
batch_2_A_AAATGGACATATCTGG-1                    4701  0h_A   iPSC_99_4   
...                                              ...   ...         ...   
batch_1_sample_120H_TTTACTGCATCCGCGA-1          4629  120h   iPSC_72_1   
batch_1_sample_120H_TTTCACATCAGCCCAG-1          5140  120h   iPSC_72_1   
batch_1_sample_120H_TTTCAGTAGTACAGAT-1          5437  120h   iPSC_72_1   
batch_1_sample_120H_TTTGATCAGCTCCATA-1          4127  120h   iPSC_72_1   
batch_1_sample_120H_TTTGTTGAGTTGGCGA-1          5614  120h   iPSC_72_1   

                                        percent.mt  percent.dissoc  \
batch_2_A_AAACCCAAGGTAATCA-1              5.110027        0.013308   
batch_2_A_AAAGGATCATCCAATG-1              0.201465        0.015073   
batch_2_A_AAAGGATGTGGTCAAG-1              4.097389        0.014101   
batch_2_A_AAAGGTAGTGTCATCA-1              4.532912        0.013420   
batch_2_A_AAATGGACATATCTGG-1              4.932110        0.013176   
...                                            ...             ...   
batch_1_sample_120H_TTTACTGCATCCGCGA-1    4.767002        0.017398   
batch_1_sample_120H_TTTCACATCAGCCCAG-1    4.127899        0.014142   
batch_1_sample_120H_TTTCAGTAGTACAGAT-1    2.035554        0.013721   
batch_1_sample_120H_TTTGATCAGCTCCATA-1    3.428081        0.015297   
batch_1_sample_120H_TTTGTTGAGTTGGCGA-1    2.722464        0.013653   

                                       RNA_snn_res.0.3 seurat_clusters  \
batch_2_A_AAACCCAAGGTAATCA-1                         2               0   
batch_2_A_AAAGGATCATCCAATG-1                         7               0   
batch_2_A_AAAGGATGTGGTCAAG-1                         2               0   
batch_2_A_AAAGGTAGTGTCATCA-1                         2               0   
batch_2_A_AAATGGACATATCTGG-1                         2               0   
...                                                ...             ...   
batch_1_sample_120H_TTTACTGCATCCGCGA-1               3               2   
batch_1_sample_120H_TTTCACATCAGCCCAG-1               5               4   
batch_1_sample_120H_TTTCAGTAGTACAGAT-1               3               2   
batch_1_sample_120H_TTTGATCAGCTCCATA-1               3               2   
batch_1_sample_120H_TTTGTTGAGTTGGCGA-1               3               2   

                                        RNA_snn_res.0.22  
batch_2_A_AAACCCAAGGTAATCA-1                           0  
batch_2_A_AAAGGATCATCCAATG-1                           0  
batch_2_A_AAAGGATGTGGTCAAG-1                           0  
batch_2_A_AAAGGTAGTGTCATCA-1                           0  
batch_2_A_AAATGGACATATCTGG-1                           0  
...                                                  ...  
batch_1_sample_120H_TTTACTGCATCCGCGA-1                 2  
batch_1_sample_120H_TTTCACATCAGCCCAG-1                 4  
batch_1_sample_120H_TTTCAGTAGTACAGAT-1                 2  
batch

In [33]:
sc.pp.highly_variable_genes(
    hips,
    n_top_genes=2000,
    batch_key="sample_name",
    subset=True
)

In [34]:
select_terms = hips.varm["I"].sum(0)>12
hips.uns['terms'] = np.array(hips.uns['terms'])[select_terms].tolist()
hips.varm['I'] = hips.varm['I'][:, select_terms]
hips._inplace_subset_var(hips.varm['I'].sum(1)>0)
#hips.Y = hips.obsp["distances"].copy()

In [35]:
hips

AnnData object with n_obs × n_vars = 4694 × 1968
    obs: 'orig.ident', 'nCount_RNA', 'nFeature_RNA', 'run', 'sample_name', 'percent.mt', 'percent.dissoc', 'RNA_snn_res.0.3', 'seurat_clusters', 'RNA_snn_res.0.22'
    var: 'features', 'highly_variable', 'means', 'dispersions', 'dispersions_norm', 'highly_variable_nbatches', 'highly_variable_intersection'
    uns: 'neighbors', 'terms', 'log1p', 'hvg'
    obsm: 'X_mnn', 'X_umap'
    varm: 'I'
    obsp: 'distances'

In [36]:
for i in hips.obs:
    print(hips.obs[i].values)


['SeuratProject', 'SeuratProject', 'SeuratProject', 'SeuratProject', 'SeuratProject', ..., 'SeuratProject', 'SeuratProject', 'SeuratProject', 'SeuratProject', 'SeuratProject']
Length: 4694
Categories (1, object): ['SeuratProject']
[48806.  5460. 32899. 37327. 18633. 24022. 38150. ... 11334. 10288. 14013.
 21173. 22107. 12806. 32140.]
[6892 2307 5707 6069 4701 5670 6478 ... 4117 3380 4629 5140 5437 4127 5614]
['0h_A', '0h_A', '0h_A', '0h_A', '0h_A', ..., '120h', '120h', '120h', '120h', '120h']
Length: 4694
Categories (4, object): ['0h_A', '0h_B', '48h', '120h']
['iPSC_99_4', 'iPSC_99_4', 'iPSC_99_4', 'iPSC_99_4', 'iPSC_99_4', ..., 'iPSC_72_1', 'iPSC_72_1', 'iPSC_72_1', 'iPSC_72_1', 'iPSC_72_1']
Length: 4694
Categories (4, object): ['iPSC_20_6_4', 'iPSC_54_3', 'iPSC_72_1', 'iPSC_99_4']
[5.11 0.2  4.1  4.53 4.93 6.64 6.03 ... 7.36 3.35 4.77 4.13 2.04 3.43 2.72]
[0.01 0.02 0.01 0.01 0.01 0.01 0.01 ... 0.02 0.02 0.02 0.01 0.01 0.02 0.01]
['2', '7', '2', '2', '2', ..., '3', '5', '3', '3', '3

In [55]:
intr_cvae = sca.models.EXPIMAP(
    adata=hips,
    condition_key='sample_name',
    hidden_layer_sizes=[256, 256, 256],
    #use_mmd=False,
    recon_loss='nb',
    mask=hips.varm['I'].T,
    #use_decoder_relu=False,
    #mmd_instead_kl=False
)



INITIALIZING NEW NETWORK..............
Encoder Architecture:
	Input Layer in, out and cond: 1968 256 4
	Hidden Layer 1 in/out: 256 256
	Hidden Layer 2 in/out: 256 256
	Mean/Var Layer in/out: 256 245
Decoder Architecture:
	Masked linear layer in, ext_m, ext, cond, out:  245 0 0 4 1968
	with hard mask.
Last Decoder layer: softmax


In [52]:
hips.X = hips.X.astype(np.float32)

In [56]:
early_stopping_kwargs = {
    "early_stopping_metric": "val_unweighted_loss", # val_unweighted_loss
    "threshold": 0,
    "patience": 50,
    "reduce_lr": True,
    "lr_patience": 13,
    "lr_factor": 0.1,
}

In [61]:
ALPHA = 0.7
OMEGA = None

In [62]:

intr_cvae.train(
    n_epochs=400, 
    alpha_epoch_anneal=100, 
    alpha=ALPHA, 
    omega=OMEGA,
    alpha_kl=0.5,
    weight_decay=0., 
    early_stopping_kwargs=early_stopping_kwargs,
    use_early_stopping=True,
    seed=2020
)

Preparing (4694, 1968)
Instantiating dataset
Init the group lasso proximal operator for the main terms.
 |███████████████████-| 99.2%  - val_loss: 1239.4485168457 - val_recon_loss: 1223.0694274902 - val_kl_loss: 32.75814819345
ADJUSTED LR
 |████████████████████| 100.0%  - val_loss: 1239.4542236328 - val_recon_loss: 1222.9104614258 - val_kl_loss: 33.0874900818
Saving best state of network...
Best State was in Epoch 382


In [63]:
inactive_idx = ~(intr_cvae.model.decoder.L0.expr_L.weight.data.norm(p=2, dim=0)>0).cpu().numpy()